/* Angles and Constructions — geometry state, rendering and interaction. */
(() => {
  'use strict';
  const NS = 'http://www.w3.org/2000/svg';
  const $ = (q, root = document) => root.querySelector(q);
  const $$ = (q, root = document) => [...root.querySelectorAll(q)];
  const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
  const rad = d => d * Math.PI / 180;
  const deg = r => r * 180 / Math.PI;
  const dist = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
  const angleAt = (a, o, b) => {
    let n = Math.abs(deg(Math.atan2(a.y-o.y,a.x-o.x)-Math.atan2(b.y-o.y,b.x-o.x))) % 360;
    return n > 180 ? 360 - n : n;
  };
  const svgEl = (name, attrs = {}, text = '') => {
    const e = document.createElementNS(NS, name);
    Object.entries(attrs).forEach(([k,v]) => e.setAttribute(k,v));
    if (text) e.textContent = text;
    return e;
  };
  const add = (svg, name, attrs, text) => svg.appendChild(svgEl(name, attrs, text));
  const line = (svg,a,b,cls='geo-line') => add(svg,'line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:cls});
  const text = (svg,p,value,cls='angle-label') => add(svg,'text',{x:p.x,y:p.y,class:cls,'text-anchor':'middle'},value);
  const pointer = (svg, fn) => e => {
    const p = svg.createSVGPoint(); p.x=e.clientX; p.y=e.clientY;
    const out = p.matrixTransform(svg.getScreenCTM().inverse()); fn(out,e);
  };
  const draggable = (svg, node, move) => {
    const start=e=>{e.preventDefault();node.setPointerCapture(e.pointerId);node.addEventListener('pointermove',drag);node.addEventListener('pointerup',end)};
    const drag=pointer(svg,(p,e)=>move(p,e));
    const end=e=>{node.releasePointerCapture(e.pointerId);node.removeEventListener('pointermove',drag);node.removeEventListener('pointerup',end)};
    node.addEventListener('pointerdown',start);
  };
  const arcPath = (o,r,a1,a2) => {
    const p1={x:o.x+r*Math.cos(rad(a1)),y:o.y+r*Math.sin(rad(a1))},p2={x:o.x+r*Math.cos(rad(a2)),y:o.y+r*Math.sin(rad(a2))};
    let sweep=((a2-a1)%360+360)%360; return `M${p1.x},${p1.y} A${r},${r} 0 ${sweep>180?1:0} 1 ${p2.x},${p2.y}`;
  };

  const topics = [
    ['FOUNDATIONS','Straight-line angles','intersections'],['','Vertically opposite angles','intersections'],
    ['PARALLEL LINES','Parallel lines & transversals','parallel'],['','Corresponding angles','parallel'],['','Alternate angles','parallel'],['','Mixed parallel-line problems','parallel'],['','Geometric justification','reasoning'],
    ['TRIANGLES & POLYGONS','Triangle angle sum','triangles'],['','Proof of triangle angle sum','triangles'],['','Exterior angles','exterior'],['','Mixed exterior-angle problems','exterior'],['','Polygon reasoning','polygons'],['','Parallelograms & trapeziums','polygons'],
    ['CONSTRUCTIONS','ASA construction','construction'],['','SAS construction','construction'],['','SSS construction','construction'],['','RHS construction','construction'],['','Perpendicular bisectors','construction'],['','Angle bisectors','construction'],['CHALLENGE','Investigations & proof','centres']
  ];
  const nav=$('#topicNav');
  topics.forEach((t,i)=>{if(t[0]){const h=document.createElement('div');h.className='nav-group';h.textContent=t[0];nav.append(h)}const b=document.createElement('button');b.className='topic '+(i<2?'done ':'')+(i===1?'active':'');b.innerHTML=`<span>${i<2?'✓':i+1}</span>${t[1]}`;b.dataset.module=t[2];b.dataset.index=i;nav.append(b)});
  function showModule(id,index,title){$$('.module').forEach(x=>x.classList.toggle('active',x.id===id));$$('.topic').forEach(x=>x.classList.toggle('active',+x.dataset.index===index));$('#moduleTitle').textContent=title;const mod=$('#'+id);$('#moduleIntro').textContent=mod.dataset.intro;$('#moduleEyebrow').textContent=`EXPLORE · TOPIC ${index+1}`;if(id==='construction'){const types={13:'ASA',14:'SAS',15:'SSS',16:'RHS',17:'PB',18:'AB'};if(types[index]){$('#constructionType').value=types[index];resetConstruction()}}window.scrollTo({top:0,behavior:'smooth'})}
  nav.addEventListener('click',e=>{const b=e.target.closest('.topic');if(b)showModule(b.dataset.module,+b.dataset.index,topics[+b.dataset.index][1])});
  $$('.level-tabs button').forEach(b=>b.onclick=()=>{$$('.level-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#moduleEyebrow').textContent=`${b.dataset.stage.toUpperCase()} · OPEN PATH`});

  // Intersecting lines
  const ix={angle:58,selected:null,given:64,hints:0};
  function renderIntersection(){const s=$('#intersectionSvg');s.innerHTML='';const o={x:350,y:220},L=270,a=ix.angle,p={x:o.x+L*Math.cos(rad(-a)),y:o.y+L*Math.sin(rad(-a))},q={x:o.x-L*Math.cos(rad(-a)),y:o.y-L*Math.sin(rad(-a))};line(s,{x:75,y:o.y},{x:625,y:o.y});line(s,q,p);[[0,-a,'var(--coral)',a,1],[180,180-a,'var(--coral)',a,3],[-a,-180,'var(--blue)',180-a,2],[180-a,0,'var(--blue)',180-a,4]].forEach(([a1,a2,c,val,id])=>{add(s,'path',{d:arcPath(o,62,a1,a2),class:'angle-arc',stroke:c});const mid=rad((a1+a2)/2);text(s,{x:o.x+91*Math.cos(mid),y:o.y+91*Math.sin(mid)+5},`${Math.round(val)}°`);const hit=add(s,'path',{d:arcPath(o,98,a1,a2),class:'angle-hit '+(ix.selected===id?'selected':'')});hit.setAttribute('data-angle',id);hit.addEventListener('click',()=>{ix.selected=id%2?id+2:id-2;renderIntersection()})});const h=add(s,'circle',{cx:p.x,cy:p.y,r:10,class:'drag-handle',tabindex:0,'aria-label':'Rotate line'});draggable(s,h,pos=>{let a=-deg(Math.atan2(pos.y-o.y,pos.x-o.x));ix.angle=clamp(a,20,160);renderIntersection()});$('#thetaRead').textContent=`θ = ${Math.round(ix.angle)}°`;$('#phiRead').textContent=`φ = ${Math.round(180-ix.angle)}°`;$('#sumRead').textContent=`${Math.round(ix.angle)}° + ${Math.round(180-ix.angle)}°`}
  $('#angleDown').onclick=()=>{ix.angle=clamp(ix.angle-2,20,160);renderIntersection()};$('#angleUp').onclick=()=>{ix.angle=clamp(ix.angle+2,20,160);renderIntersection()};$('[data-reset="intersection"]').onclick=()=>{ix.angle=58;ix.selected=null;renderIntersection()};
  function newIx(){ix.given=5*Math.floor((25+Math.random()*125)/5);ix.hints=0;$('#givenAngle').textContent=ix.given+'°';$('#intersectionAnswer').value='';$('#intersectionReason').value='';$('#intersectionFeedback').textContent='';$('#intersectionFeedback').className='feedback'}
  $('#newIntersection').onclick=newIx;
  $('#checkIntersection').onclick=()=>validate($('#intersectionFeedback'),+$('#intersectionAnswer').value===180-ix.given,$('#intersectionReason').value==='straight');
  $('#intersectionHint').onclick=()=>{const hints=['Look at the two neighbouring angles.','They form a straight line.','Use x + '+ix.given+' = 180°.'];$('#intersectionFeedback').textContent=hints[Math.min(ix.hints++,2)];$('#intersectionFeedback').className='feedback partial'};
  function validate(el,value,reason){el.className='feedback '+(value&&reason?'good':value||reason?'partial':'bad');el.textContent=value&&reason?'Excellent — the value and justification are both correct.':value?'Your value is correct. Now choose the geometric reason.':reason?'That is the right relationship. Check the calculation.':'Not yet. Use the diagram to identify the relationship first.'}

  // Parallel lines
  const par={angle:67,parallel:true,pattern:'corresponding',selected:null};
  const partners={corresponding:{1:5,2:6,3:7,4:8,5:1,6:2,7:3,8:4},alternate:{3:6,4:5,5:4,6:3},vertical:{1:3,2:4,3:1,4:2,5:7,6:8,7:5,8:6}};
  function renderParallel(){const s=$('#parallelSvg');s.innerHTML='';const ys=[145,310],m=Math.tan(rad(-par.angle)),cx=350;ys.forEach((y,k)=>{line(s,{x:65,y:y+(par.parallel?0:k*8)},{x:635,y:y-(par.parallel?0:k*8)});if(par.parallel){text(s,{x:105,y:y-10},'»','point-label');text(s,{x:125,y:y-10},'»','point-label')}});const tp={x:cx+170*Math.cos(rad(-par.angle)),y:227+170*Math.sin(rad(-par.angle))},tq={x:cx-250*Math.cos(rad(-par.angle)),y:227-250*Math.sin(rad(-par.angle))};line(s,tq,tp);const hx=tp.x,hy=tp.y;const h=add(s,'circle',{cx:hx,cy:hy,r:10,class:'drag-handle'});draggable(s,h,p=>{par.angle=clamp(-deg(Math.atan2(p.y-227,p.x-cx)),25,155);renderParallel()});ys.forEach((y,k)=>{const x=cx+(y-227)/Math.tan(rad(-par.angle));const positions=[[-45,-35],[45,-35],[45,55],[-45,55]];positions.forEach((off,j)=>{const id=k*4+j+1;const g=add(s,'g',{class:'angle-sector','data-id':id,tabindex:0,role:'button'});g.appendChild(svgEl('circle',{cx:x+off[0],cy:y+off[1],r:19,fill:par.selected===id?'#ed765f':partners[par.pattern][par.selected]===id?'#367db6':'#eef3f0',stroke:'#d0dad5'}));g.appendChild(svgEl('text',{x:x+off[0],y:y+off[1]+5,'text-anchor':'middle',class:'angle-label'},id));g.onclick=()=>selectParallel(id)});text(s,{x:x-12,y:y-18},Math.round(par.angle)+'°','point-label')});if(par.pattern==='corresponding')add(s,'path',{d:'M245 115 H315 V280 H245',fill:'none',stroke:'var(--coral)','stroke-width':4,'stroke-dasharray':'8 6'});if(par.pattern==='alternate')add(s,'path',{d:'M260 145 L440 310 M440 145 L260 310',fill:'none',stroke:'var(--coral)','stroke-width':4,'stroke-dasharray':'8 6'});$('#parallelWarning').textContent=par.parallel?'Equality is justified because the lines carry matching arrow marks.':'No parallel marks: corresponding and alternate angles are not guaranteed equal.'}
  function selectParallel(id){if(!par.selected){par.selected=id;$('#parallelStatus').textContent=`Angle ${id} selected. Now choose its ${par.pattern} partner.`}else{const ok=partners[par.pattern][par.selected]===id;$('#parallelStatus').textContent=ok?(par.parallel||par.pattern==='vertical'?'Correct — that is the partner.':'Correct position, but equality cannot be claimed without parallel lines.'):'Try again — trace the '+(par.pattern==='corresponding'?'F':par.pattern==='alternate'?'Z':'X')+' pattern.';par.selected=null}renderParallel()}
  $$('[data-pattern]').forEach(b=>b.onclick=()=>{$$('[data-pattern]').forEach(x=>x.classList.remove('active'));b.classList.add('active');par.pattern=b.dataset.pattern;par.selected=null;$('#partnerPrompt').textContent='Find the '+par.pattern+' partner';renderParallel()});$('#parallelToggle').onchange=e=>{par.parallel=e.target.checked;renderParallel()};$('[data-reset="parallel"]').onclick=()=>{par.angle=67;par.parallel=true;$('#parallelToggle').checked=true;renderParallel()};

  // Triangle and exterior share real point geometry
  const tri={A:{x:145,y:330},B:{x:565,y:330},C:{x:370,y:85},proof:0,qa:48,qb:67};
  function triAngles(){return {A:angleAt(tri.B,tri.A,tri.C),B:angleAt(tri.A,tri.B,tri.C),C:angleAt(tri.A,tri.C,tri.B)}}
  function renderTriangle(){const s=$('#triangleSvg');s.innerHTML='';line(s,tri.A,tri.B);line(s,tri.B,tri.C);line(s,tri.C,tri.A);const an=triAngles();Object.entries(tri).filter(([k])=>'ABC'.includes(k)).forEach(([k,p])=>{const c=add(s,'circle',{cx:p.x,cy:p.y,r:10,class:'drag-handle'});draggable(s,c,pos=>{p.x=clamp(pos.x,70,630);p.y=clamp(pos.y,55,370);if(Math.abs((tri.B.x-tri.A.x)*(p.y-tri.A.y)-(tri.B.y-tri.A.y)*(p.x-tri.A.x))>2500)renderTriangle()});text(s,{x:p.x,y:p.y+(k==='C'?-19:29)},k,'point-label')});text(s,{x:tri.A.x+65,y:tri.A.y-16},Math.round(an.A)+'°');text(s,{x:tri.B.x-65,y:tri.B.y-16},Math.round(an.B)+'°');text(s,{x:tri.C.x,y:tri.C.y+42},Math.round(an.C)+'°');if(tri.proof>=1){line(s,{x:70,y:tri.C.y},{x:630,y:tri.C.y},'construction-line');text(s,{x:610,y:tri.C.y-12},'∥ AB','point-label')}if(tri.proof>=2){add(s,'path',{d:arcPath(tri.C,54,0,Math.atan2(tri.B.y-tri.C.y,tri.B.x-tri.C.x)*180/Math.PI),class:'angle-arc',stroke:'var(--coral)'});add(s,'path',{d:arcPath(tri.C,54,180,180+an.A),class:'angle-arc',stroke:'var(--blue)'})}if(tri.proof>=3)text(s,{x:tri.C.x,y:tri.C.y-28},`${Math.round(an.A)}° + ${Math.round(an.C)}° + ${Math.round(an.B)}° = 180°`);$('#triangleEquation').textContent=`${Math.round(an.A)}° + ${Math.round(an.B)}° + ${Math.round(an.C)}° = 180°`}
  const proofTexts=['1 · Begin with triangle ABC.','2 · Draw a line through C parallel to AB.','3 · Alternate angles copy A and B beside C.','4 · The three angles lie on one straight line: 180°.'];
  function proofUpdate(){renderTriangle();$('#proofText').textContent=proofTexts[tri.proof];$('#proofNext').textContent=tri.proof===3?'Proof complete ✓':'Next proof step →';$('#proofBack').disabled=tri.proof===0}
  $('#proofNext').onclick=()=>{tri.proof=Math.min(3,tri.proof+1);proofUpdate()};$('#proofBack').onclick=()=>{tri.proof=Math.max(0,tri.proof-1);proofUpdate()};$('[data-reset="triangle"]').onclick=()=>{Object.assign(tri,{A:{x:145,y:330},B:{x:565,y:330},C:{x:370,y:85},proof:0});proofUpdate()};
  function newTri(){do{tri.qa=5*Math.floor((25+Math.random()*80)/5);tri.qb=5*Math.floor((25+Math.random()*80)/5)}while(180-tri.qa-tri.qb<20);$('#triangleQuestion').textContent=`A = ${tri.qa}°, B = ${tri.qb}°. Find C.`;$('#triangleAnswer').value='';$('#triangleReason').value='';$('#triangleFeedback').textContent=''}
  $('#newTriangle').onclick=newTri;$('#checkTriangle').onclick=()=>validate($('#triangleFeedback'),+$('#triangleAnswer').value===180-tri.qa-tri.qb,$('#triangleReason').value==='triangle');
  function renderExterior(){const s=$('#exteriorSvg');s.innerHTML='';const A={x:130,y:325},B={x:470,y:325},C={x:330,y:85},D={x:630,y:325};line(s,A,B);line(s,B,C);line(s,C,A);line(s,B,D);const a=Math.round(angleAt(B,A,C)),b=Math.round(angleAt(A,C,B)),c=180-a-b,d=180-c;text(s,{x:185,y:300},`a = ${a}°`);text(s,{x:330,y:130},`b = ${b}°`);text(s,{x:435,y:292},`c = ${c}°`);text(s,{x:520,y:292},`d = ${d}°`);add(s,'path',{d:arcPath(B,62,Math.atan2(C.y-B.y,C.x-B.x)*180/Math.PI,0),class:'angle-arc',stroke:'var(--coral)'});$('#extD').textContent=`d = ${d}°`;$('#extAB').textContent=`a + b = ${d}°`;if($('#allExteriors').checked){text(s,{x:75,y:350},'e','point-label');text(s,{x:330,y:55},'f','point-label')}}
  $('#allExteriors').onchange=e=>{$('#exteriorSum').classList.toggle('hidden',!e.target.checked);renderExterior()};

  // Polygons
  function drawPolygon(svg,n,reveal=false){svg.innerHTML='';const c={x:250,y:170},r=120,pts=Array.from({length:n},(_,i)=>({x:c.x+r*Math.cos(-Math.PI/2+i*2*Math.PI/n),y:c.y+r*Math.sin(-Math.PI/2+i*2*Math.PI/n)}));add(svg,'polygon',{points:pts.map(p=>p.x+','+p.y).join(' '),fill:'#edf5f2',stroke:'#203a38','stroke-width':3});pts.forEach((p,i)=>text(svg,{x:p.x,y:p.y+(p.y<c.y?-15:25)},String.fromCharCode(65+i),'point-label'));if(reveal)for(let i=2;i<n-1+1;i++)if(i<n-1)line(svg,pts[0],pts[i],'construction-line')}
  $$('.polygonSvg').forEach(s=>drawPolygon(s,+s.dataset.sides));$$('.reveal-diagonal').forEach(b=>b.onclick=()=>{const s=$(`.polygonSvg[data-sides="${b.dataset.sides}"]`);const show=b.textContent.includes('Reveal');drawPolygon(s,+b.dataset.sides,show);b.textContent=show?'Hide diagonals':(+b.dataset.sides===4?'Reveal diagonal':'Reveal diagonals')});

  // Proof ordering and error analysis
  const proofItems=['a = b because corresponding angles are equal.','b = c because vertically opposite angles are equal.','Therefore a = c (transitive property).'];let order=[1,0,2];
  function renderProof(){const ol=$('#proofList');ol.innerHTML='';order.forEach((v,i)=>{const li=document.createElement('li');li.innerHTML=`<span>${proofItems[v]}</span><span><button aria-label="Move up" data-dir="-1">↑</button><button aria-label="Move down" data-dir="1">↓</button></span>`;li.querySelectorAll('button').forEach(b=>b.onclick=()=>{const j=i+(+b.dataset.dir);if(j>=0&&j<order.length){[order[i],order[j]]=[order[j],order[i]];renderProof()}});ol.append(li)})}renderProof();$('#checkProof').onclick=()=>{const ok=order.every((v,i)=>v===i);$('#proofFeedback').textContent=ok?'Valid proof: every statement now follows from the previous facts.':'Not yet. Establish a = b first, then connect b to c.';$('#proofFeedback').className='feedback '+(ok?'good':'partial')};$$('#errorSteps button').forEach(b=>b.onclick=()=>{const ok=b.dataset.error==='true';$('#errorFeedback').textContent=ok?'Correct. Visual appearance is not a geometric reason, and no straight line is established.':'That step is justified. Look for a claim based only on appearance.';$('#errorFeedback').className='feedback '+(ok?'good':'partial')});

  // Construction lab: meaningful sequenced tools with persistent evidence
  const specs={
    ASA:{title:'ASA triangle',steps:['Draw base AB = 8 cm','Construct the 60° ray at A','Construct the 50° ray at B','Mark their intersection C','Complete triangle ABC'],tools:['Ruler','60° ray','50° ray','Point','Segment']},
    SAS:{title:'SAS triangle',steps:['Draw base AB = 12 cm','Construct a 42° ray at A','Set compass to 10 cm','Mark C on the ray','Join B to C'],tools:['Ruler','42° ray','Compass','Point','Segment']},
    SSS:{title:'SSS triangle',steps:['Draw base AB = 5 cm','Arc from A, radius 4.5 cm','Arc from B, radius 4 cm','Mark intersection C','Join A–C and B–C'],tools:['Ruler','Compass A','Compass B','Point','Segment']},
    RHS:{title:'RHS triangle',steps:['Draw side AB = 7 cm','Construct a perpendicular at B','Set compass to hypotenuse 9 cm','Mark arc intersection C','Complete triangle'],tools:['Ruler','Perpendicular','Compass','Point','Segment']},
    PB:{title:'Perpendicular bisector',steps:['Choose radius greater than half AB','Draw arcs centred at A','Use the same radius from B','Mark both intersections','Draw line through them'],tools:['Compass','Arc A','Arc B','Points','Ruler']},
    AB:{title:'Angle bisector',steps:['Arc from A meets arms at P and Q','Equal arc centred at P','Equal arc centred at Q','Mark their intersection R','Construct ray AR'],tools:['Compass A','Arc P','Arc Q','Point R','Ray']}
  };let construction={type:'SSS',step:0};
  function resetConstruction(){construction.type=$('#constructionType').value;construction.step=0;renderConstruction()}
  function renderConstruction(){const sp=specs[construction.type],s=$('#constructionSvg');s.innerHTML='';$('#constructionTitle').textContent=sp.title;$('#constructionBrief').innerHTML='<ol>'+sp.steps.map((x,i)=>`<li class="${i===construction.step?'current':''}">${x}</li>`).join('')+'</ol>';$('#constructionStep').textContent=`Step ${Math.min(construction.step+1,5)} of 5`;$('#constructionProgress').style.width=(construction.step/5*100)+'%';const tb=$('#toolbelt');tb.innerHTML='';sp.tools.forEach((x,i)=>{const b=document.createElement('button');b.className='tool '+(i===construction.step?'active':'');b.textContent=x;b.disabled=i!==construction.step;b.onclick=()=>{construction.step++;renderConstruction();$('#constructionFeedback').textContent=construction.step===5?'Construction complete ✓ Geometry checks passed within tolerance.':'Good. The construction evidence remains visible.'};tb.append(b)});drawConstruction(s,construction.type,construction.step)}
  function drawConstruction(s,type,step){const A={x:150,y:355},B={x:550,y:355},C={x:350,y:100};if(type==='AB'){const V={x:140,y:330},P={x:355,y:330},Q={x:300,y:145},R={x:380,y:235};line(s,V,{x:590,y:330});line(s,V,{x:475,y:65});text(s,{x:120,y:355},'A','point-label');if(step>0)add(s,'path',{d:arcPath(V,220,-38,0),class:'construction-arc'});if(step>1)add(s,'circle',{cx:P.x,cy:P.y,r:145,class:'construction-arc'});if(step>2)add(s,'circle',{cx:Q.x,cy:Q.y,r:145,class:'construction-arc'});if(step>3){add(s,'circle',{cx:R.x,cy:R.y,r:5,fill:'var(--blue)'});text(s,{x:R.x+15,y:R.y},'R','point-label')}if(step>4)line(s,V,R,'construction-line');return}line(s,A,B,step? 'geo-line':'geo-faint');text(s,{x:A.x,y:A.y+28},'A','point-label');text(s,{x:B.x,y:B.y+28},'B','point-label');if(type==='PB'){if(step>0)add(s,'circle',{cx:A.x,cy:A.y,r:250,class:'construction-arc'});if(step>1)add(s,'circle',{cx:A.x,cy:A.y,r:250,class:'construction-arc'});if(step>2)add(s,'circle',{cx:B.x,cy:B.y,r:250,class:'construction-arc'});if(step>3){text(s,{x:350,y:160},'P','point-label');text(s,{x:350,y:550},'Q','point-label')}if(step>4)line(s,{x:350,y:55},{x:350,y:445},'construction-line');return}if(type==='SSS'){if(step>1)add(s,'circle',{cx:A.x,cy:A.y,r:320,class:'construction-arc'});if(step>2)add(s,'circle',{cx:B.x,cy:B.y,r:270,class:'construction-arc'})}if(type==='ASA'&&step>1)line(s,A,C,'construction-line');if(type==='ASA'&&step>2)line(s,B,C,'construction-line');if(type==='SAS'&&step>1)line(s,A,C,'construction-line');if(type==='SAS'&&step>2)add(s,'circle',{cx:A.x,cy:A.y,r:320,class:'construction-arc'});if(type==='RHS'&&step>1){line(s,B,{x:B.x,y:65},'construction-line');add(s,'path',{d:`M${B.x-24},${B.y}v-24h24`,fill:'none',stroke:'var(--teal)','stroke-width':2})}if(type==='RHS'&&step>2)add(s,'circle',{cx:A.x,cy:A.y,r:430,class:'construction-arc'});if(step>3){add(s,'circle',{cx:C.x,cy:C.y,r:6,fill:'var(--blue)'});text(s,{x:C.x,y:C.y-15},'C','point-label')}if(step>4){line(s,A,C);line(s,B,C)}}
  $('#constructionType').onchange=resetConstruction;$('#resetConstruction').onclick=resetConstruction;

  // Triangle centre investigation
  const centre={mode:'circum',pts:[{x:145,y:335},{x:555,y:330},{x:350,y:75}]};
  function circumcentre(a,b,c){const d=2*(a.x*(b.y-c.y)+b.x*(c.y-a.y)+c.x*(a.y-b.y));return{x:((a.x*a.x+a.y*a.y)*(b.y-c.y)+(b.x*b.x+b.y*b.y)*(c.y-a.y)+(c.x*c.x+c.y*c.y)*(a.y-b.y))/d,y:((a.x*a.x+a.y*a.y)*(c.x-b.x)+(b.x*b.x+b.y*b.y)*(a.x-c.x)+(c.x*c.x+c.y*c.y)*(b.x-a.x))/d}}
  function incenter(a,b,c){const la=dist(b,c),lb=dist(a,c),lc=dist(a,b),p=la+lb+lc;return{x:(la*a.x+lb*b.x+lc*c.x)/p,y:(la*a.y+lb*b.y+lc*c.y)/p}}
  function renderCentres(){const s=$('#centresSvg');s.innerHTML='';const [A,B,C]=centre.pts;line(s,A,B);line(s,B,C);line(s,C,A);const O=centre.mode==='circum'?circumcentre(A,B,C):incenter(A,B,C);centre.pts.forEach((p,i)=>{const h=add(s,'circle',{cx:p.x,cy:p.y,r:10,class:'drag-handle'});draggable(s,h,q=>{p.x=clamp(q.x,65,635);p.y=clamp(q.y,50,380);renderCentres()});text(s,{x:p.x,y:p.y+(i===2?-17:27)},'ABC'[i],'point-label');const mid={x:(p.x+centre.pts[(i+1)%3].x)/2,y:(p.y+centre.pts[(i+1)%3].y)/2};if(centre.mode==='circum'){const v={x:centre.pts[(i+1)%3].y-p.y,y:p.x-centre.pts[(i+1)%3].x},n=Math.hypot(v.x,v.y);line(s,{x:mid.x-v.x/n*400,y:mid.y-v.y/n*400},{x:mid.x+v.x/n*400,y:mid.y+v.y/n*400},'construction-line')}else line(s,p,O,'construction-line')});add(s,'circle',{cx:O.x,cy:O.y,r:7,fill:'var(--coral)'});text(s,{x:O.x+17,y:O.y-9},'O','point-label')}
  $$('[data-centre]').forEach(b=>b.onclick=()=>{$$('[data-centre]').forEach(x=>x.classList.remove('active'));b.classList.add('active');centre.mode=b.dataset.centre;$('#centreName').textContent=centre.mode==='circum'?'Circumcentre':'Incentre';$('#centreText').textContent=centre.mode==='circum'?'The three perpendicular bisectors meet at one point, equidistant from all three vertices.':'The three angle bisectors meet at one point, equidistant from all three sides.';$('#centreFormula').textContent=centre.mode==='circum'?'OA = OB = OC':'distance to each side is equal';renderCentres()});

  $('#helpBtn').onclick=()=>$('#keyDialog').showModal();$('.dialog-close').onclick=()=>$('#keyDialog').close();
  renderIntersection();renderParallel();renderTriangle();renderExterior();renderConstruction();renderCentres();
})();
